LEFT = "L"
RIGHT = "R"
UP = "U"
DOWN = "D"

def sequence(start, command, keys):
    digit = start
    for key in command:
        digit = keys[digit][key]
    return digit


keys1 = {
    1:{LEFT:1, UP:1, RIGHT:2, DOWN:4},
    2:{LEFT:1, UP:2, RIGHT:3, DOWN:5},
    3:{LEFT:2, UP:3, RIGHT:3, DOWN:6},
    4:{LEFT:4, UP:1, RIGHT:5, DOWN:7},
    5:{LEFT:4, UP:2, RIGHT:6, DOWN:8},
    6:{LEFT:5, UP:3, RIGHT:6, DOWN:9},
    7:{LEFT:7, UP:4, RIGHT:8, DOWN:7},
    8:{LEFT:7, UP:5, RIGHT:9, DOWN:8},
    9:{LEFT:8, UP:6, RIGHT:9, DOWN:9}}

"""
    1
  2 3 4
5 6 7 8 9
  A B C
    D
"""

A = 10
B = 11
C = 12
D = 13

keys2 = {
    1:{LEFT:1, UP:1, RIGHT:1, DOWN:3},
    2:{LEFT:2, UP:2, RIGHT:3, DOWN:6},
    3:{LEFT:2, UP:1, RIGHT:4, DOWN:7},
    4:{LEFT:3, UP:4, RIGHT:4, DOWN:8},
    5:{LEFT:5, UP:5, RIGHT:6, DOWN:5},
    6:{LEFT:5, UP:2, RIGHT:7, DOWN:A},
    7:{LEFT:6, UP:3, RIGHT:8, DOWN:B},
    8:{LEFT:7, UP:4, RIGHT:9, DOWN:C},
    9:{LEFT:8, UP:9, RIGHT:9, DOWN:9},
    A:{LEFT:A, UP:6, RIGHT:B, DOWN:A},
    B:{LEFT:A, UP:7, RIGHT:C, DOWN:D},
    C:{LEFT:B, UP:8, RIGHT:C, DOWN:C},
    D:{LEFT:D, UP:B, RIGHT:D, DOWN:D}
    }

TEST = """ULL
RRDDD
LURDL
UUUUD"""

INPUT = """LLLRLLULLDDLDUDRDDURLDDRDLRDDRUULRULLLDLUURUUUDLUUDLRUDLDUDURRLDRRRUULUURLUDRURULRLRLRRUULRUUUDRRDDRLLLDDLLUDDDLLRLLULULRRURRRLDRLDLLRURDULLDULRUURLRUDRURLRRDLLDDURLDDLUDLRLUURDRDRDDUURDDLDDDRUDULDLRDRDDURDLUDDDRUDLUDLULULRUURLRUUUDDRLDULLLUDLULDUUDLDLRRLLLRLDUDRUULDLDRDLRRDLDLULUUDRRUDDDRDLRLDLRDUDRULDRDURRUULLUDURURUUDRDRLRRDRRDRDDDDLLRURULDURDLUDLUULDDLLLDULUUUULDUDRDURLURDLDDLDDUULRLUUDLDRUDRURURRDDLURURDRLRLUUUURLLRR
UUUUURRRURLLRRDRLLDUUUUDDDRLRRDRUULDUURURDRLLRRRDRLLUDURUDLDURURRLUDLLLDRDUDRDRLDRUDUDDUULLUULLDUDUDDRDUUUDLULUDUULLUUULURRUDUULDUDDRDURRLDDURLRDLULDDRUDUDRDULLRLRLLUUDDURLUUDLRUUDDLLRUURDUDLLDRURLDURDLRDUUDLRLLRLRURRUDRRLRDRURRRUULLUDLDURDLDDDUUDRUUUDULLLRDRRDRLURDDRUUUDRRUUDLUDDDRRRRRLRLDLLDDLRDURRURLLLULURULLULRLLDDLDRLDULLDLDDDRLUDDDUDUDRRLRDLLDULULRLRURDLUDDLRUDRLUURRURDURDRRDRULUDURRLULUURDRLDLRUDLUDRURLUDUUULRRLRRRULRRRLRLRLULULDRUUDLRLLRLLLURUUDLUDLRURUDRRLDLLULUDRUDRLLLRLLDLLDUDRRURRLDLUUUURDDDUURLLRRDRUUURRRDRUDLLULDLLDLUDRRDLLDDLDURLLDLLDLLLDR
LRDULUUUDLRUUUDURUUULLURDRURDRRDDDLRLRUULDLRRUDDLLUURLDRLLRUULLUDLUDUDRDRDLUUDULLLLRDDUDRRRURLRDDLRLDRLULLLRUUULURDDLLLLRURUUDDDLDUDDDDLLLURLUUUURLRUDRRLLLUUULRDUURDLRDDDUDLLRDULURURUULUDLLRRURDLUULUUDULLUDUUDURLRULRLLDLUULLRRUDDULRULDURRLRRLULLLRRDLLDDLDUDDDUDLRUURUDUUUDDLRRDLRUDRLLRDRDLURRLUDUULDRRUDRRUDLLLLRURRRRRUULULLLRDRDUDRDDURDLDDUURRURLDRRUDLRLLRRURULUUDDDLLLRDRLULLDLDDULDLUUDRURULLDLLLLDRLRRLURLRULRDLLULUDRDR
RURRRUDLURRURLURDDRULLDRDRDRRULRRDLDDLDUUURUULLRRDRLDRRDRULLURRRULLLDULDDDDLULRUULRURUDURDUDRLRULLLRDURDDUDDRDLURRURUURDLDDDDDURURRURLLLDDLDRRDUDDLLLDRRLDDUUULDLLDRUURUDDRRLDUULRRDDUDRUULRLDLRLRUURLLDRDLDRLURULDLULDRULURLLRRLLDDDURLRUURUULULRLLLULUDULUUULDRURUDDDUUDDRDUDUDRDLLLRDULRLDLRRDRRLRDLDDULULRLRUUDDUDRRLUDRDUUUDRLLLRRLRUDRRLRUUDDLDURLDRRRUDRRDUDDLRDDLULLDLURLUUDLUDLUDLDRRLRRRULDRLRDUURLUULRDURUDUUDDURDDLRRRLUUUDURULRURLDRURULDDUDDLUDLDLURDDRRDDUDUUURLDLRDDLDULDULDDDLDRDDLUURDULLUDRRRULRLDDLRDRLRURLULLLDULLUUDURLDDULRRDDUULDRLDLULRRDULUDUUURUURDDDRULRLRDLRRURR
UDDDRLDRDULDRLRDUDDLDLLDDLUUURDDDLUDRDUDLDURLUURUDUULUUULDUURLULLRLUDLLURUUUULRLRLLLRRLULLDRUULURRLLUDUDURULLLRRRRLRUULLRDRDRRDDLUDRRUULUDRUULRDLRDRRLRRDRRRLULRULUURRRULLRRRURUDUURRLLDDDUDDULUULRURUDUDUDRLDLUULUDDLLLLDRLLRLDULLLRLLDLUUDURDLLRURUUDDDDLLUDDRLUUDUDRDRLLURURLURRDLDDDULUURURURRLUUDUDLDLDDULLURUDLRLDLRLDLDUDULURDUDRLURRRULLDDDRDRURDDLDLULUDRUULDLULRDUUURLULDRRULLUDLDRLRDDUDURRRURRLRDUULURUUDLULDLRUUULUDRDRRUDUDULLDDRLRDLURDLRLUURDRUDRDRUDLULRUDDRDLLLRLURRURRLDDDUDDLRDRRRULLUUDULURDLDRDDDLDURRLRRDLLDDLULULRRDUDUUDUULRDRRDURDDDDUUDDLUDDUULDRDDULLUUUURRRUUURRULDRRDURRLULLDU"""

commands = INPUT.split("\n")
digit = 5
result = ""
for command in commands:
    digit = sequence(digit, command, keys1)
    result += str(digit)
print result

result = ""
digit = 5
commands = INPUT.split("\n")
for command in commands:
    digit = sequence(digit, command, keys2)
    result += format(digit, "X")
print result
